//! Coverage statistics, re-implemented independently of the Python
//! `soothsayer.backtest.metrics` module.
//!
//! The re-implementation is deliberate: if the verifier reused the
//! paper's own statistics code, a bug there would self-confirm. Parity
//! with the scipy-backed Python implementation is pinned by
//! `tests/parity.rs` over a fixture generated by
//! `scripts/gen_verify_parity_fixture.py` — behaviour must stay
//! drop-in equivalent, including the boundary-case guards.

/// Survival function (1 − CDF) of the χ² distribution at integer `df`,
/// via the closed-form recurrence
/// `Q(x; ν) = Q(x; ν−2) + (x/2)^{ν/2−1} e^{−x/2} / Γ(ν/2)`,
/// anchored at `Q(x; 1) = erfc(√(x/2))` and `Q(x; 2) = e^{−x/2}`.
/// Exact for the df range this crate uses (1 … n_symbols).
pub fn chi2_sf(x: f64, df: u32) -> f64 {
    if df == 0 || x.is_nan() {
        return f64::NAN;
    }
    if x <= 0.0 {
        return 1.0;
    }
    let (mut q, mut nu) = if df % 2 == 1 {
        (libm::erfc((x / 2.0).sqrt()), 1u32)
    } else {
        ((-x / 2.0).exp(), 2u32)
    };
    while nu < df {
        nu += 2;
        let half = nu as f64 / 2.0;
        q += (x / 2.0).powf(half - 1.0) * (-x / 2.0).exp() / libm::tgamma(half);
    }
    q
}

/// Kupiec POF (proportion-of-failures) likelihood-ratio test.
/// H0: violation rate == 1 − `claimed`. Returns `(LR_uc, p)`;
/// `LR_uc ~ χ²(1)` under H0. NaN when `violations` is empty.
pub fn kupiec(violations: &[u8], claimed: f64) -> (f64, f64) {
    let n = violations.len();
    if n == 0 {
        return (f64::NAN, f64::NAN);
    }
    let x: usize = violations.iter().map(|&v| (v != 0) as usize).sum();
    let nf = n as f64;
    let xf = x as f64;
    let p_exp = 1.0 - claimed;
    let p_obs = xf / nf;
    let lr = if p_obs == 0.0 || p_obs == 1.0 {
        if p_exp == 0.0 || p_exp == 1.0 {
            return (0.0, 1.0);
        }
        2.0 * nf
            * (p_obs * (p_obs.max(1e-12) / p_exp).ln()
                + (1.0 - p_obs)
                    * ((1.0 - p_obs).max(1e-12) / (1.0 - p_exp).max(1e-12)).ln())
    } else {
        2.0 * (xf * (p_obs / p_exp).ln() + (nf - xf) * ((1.0 - p_obs) / (1.0 - p_exp)).ln())
    };
    (lr, chi2_sf(lr, 1))
}

/// Christoffersen (1998) independence test: are violations
/// Markov-independent (no clustering)? Returns `(LR_ind, p)`;
/// `LR_ind ~ χ²(1)` under H0. NaN when n < 2 or a transition
/// probability is unidentified (e.g. zero violations).
pub fn christoffersen_independence(violations: &[u8]) -> (f64, f64) {
    let n = violations.len();
    if n < 2 {
        return (f64::NAN, f64::NAN);
    }
    let (mut n00, mut n01, mut n10, mut n11) = (0f64, 0f64, 0f64, 0f64);
    for w in violations.windows(2) {
        match (w[0] != 0, w[1] != 0) {
            (false, false) => n00 += 1.0,
            (false, true) => n01 += 1.0,
            (true, false) => n10 += 1.0,
            (true, true) => n11 += 1.0,
        }
    }
    let denom0 = n00 + n01;
    let denom1 = n10 + n11;
    if denom0 == 0.0 || denom1 == 0.0 {
        return (f64::NAN, f64::NAN);
    }
    let pi01 = n01 / denom0;
    let pi11 = n11 / denom1;
    let pi = (n01 + n11) / (n00 + n01 + n10 + n11);
    let llik = |p01: f64, p11: f64| -> f64 {
        n00 * (1.0 - p01).max(1e-12).ln()
            + n01 * p01.max(1e-12).ln()
            + n10 * (1.0 - p11).max(1e-12).ln()
            + n11 * p11.max(1e-12).ln()
    };
    let lr = 2.0 * (llik(pi01, pi11) - llik(pi, pi));
    (lr, chi2_sf(lr.max(0.0), 1))
}

/// Pooled per-group independence: the sum of the computable per-group
/// `LR_ind` values is `χ²(k)` under H0, where `k` is the number of
/// groups where the test is identified. Mirrors the Python
/// `conditional_coverage_from_bounds(group_by="symbol")` pooling.
/// Returns `(LR_sum, k, p)`; `(NaN, 0, NaN)` when no group is testable.
pub fn pooled_independence(groups: &[Vec<u8>]) -> (f64, u32, f64) {
    let mut lr_sum = 0.0;
    let mut k = 0u32;
    for g in groups {
        let (lr, _) = christoffersen_independence(g);
        if lr.is_finite() {
            lr_sum += lr;
            k += 1;
        }
    }
    if k == 0 {
        return (f64::NAN, 0, f64::NAN);
    }
    (lr_sum, k, chi2_sf(lr_sum.max(0.0), k))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chi2_sf_zero_is_one() {
        for df in 1..=10 {
            assert_eq!(chi2_sf(0.0, df), 1.0);
        }
    }

    #[test]
    fn kupiec_empty_is_nan() {
        let (lr, p) = kupiec(&[], 0.95);
        assert!(lr.is_nan() && p.is_nan());
    }

    #[test]
    fn christoffersen_all_zero_is_nan() {
        let (lr, p) = christoffersen_independence(&[0; 20]);
        assert!(lr.is_nan() && p.is_nan());
    }
}
