[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
mock_chainlink_verifier_program = "G1FNffdhk83kejVjWXcHNbrX9y84nhx8EfzWu86EaKxL"
soothsayer_oracle_program = "AgXLLTmUJEVh9EsJnznU1yJaUeE9Ufe7ZotupmDqa7f6"
soothsayer_router_program = "AZE8HixpkLpqmuuZbCku5NbjWqoQLWhPRTHp8aMY9xNU"
soothsayer_streams_relay_program = "DiLqUXQPAMrX1ZoFrEqfw8mPWjpWxzhsPPQzNnEZyMFG"

[programs.localnet]
mock_chainlink_verifier_program = "G1FNffdhk83kejVjWXcHNbrX9y84nhx8EfzWu86EaKxL"
soothsayer_oracle_program = "AgXLLTmUJEVh9EsJnznU1yJaUeE9Ufe7ZotupmDqa7f6"
soothsayer_router_program = "AZE8HixpkLpqmuuZbCku5NbjWqoQLWhPRTHp8aMY9xNU"
soothsayer_streams_relay_program = "DiLqUXQPAMrX1ZoFrEqfw8mPWjpWxzhsPPQzNnEZyMFG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/soothsayer-oracle-program", "programs/soothsayer-router-program", "programs/soothsayer-streams-relay-program", "programs/mock-chainlink-verifier-program"]

[scripts]
test = "echo 'tests not yet wired — see scripts/test_oracle_program.sh when implemented'"
