//! Checkpointed adaptive cell state — Rust port of `soothsayer/adaptive_state.py`.
//!
//! The overnight profile (W15) lets the per-cell *level* adapt to realised
//! outcomes, so a served band is a function of the frozen artefact **and** a
//! published state `m[tau][cell]`. Checkpoints keep that verifiable: a read
//! verifies in one step against the checkpoint, and the checkpoint itself is
//! audited by replaying from its predecessor.
//!
//! The load-bearing thing this module must get exactly right is the
//! **canonical serialisation**. The checkpoint hash covers gamma, the clip
//! bounds and the period as well as the numbers, so a Rust verifier that
//! serialises even slightly differently would reject an *honest* checkpoint —
//! a failure mode that looks like fraud detection and is actually a port bug.
//! `tests/adaptive_parity.rs` pins byte-identical output against a fixture
//! generated by the Python implementation.
//!
//! Two details that make byte-parity achievable rather than hopeful:
//!   * every float in the pre-image is emitted as a **quoted decimal string**
//!     at fixed precision, so float repr never enters the hash;
//!   * every map is a `BTreeMap`, matching Python's `sort_keys=True` at all
//!     levels.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::error::{Error, Result};

/// Wire label for the adaptive profile. Reserves `forecaster_code = 5`.
pub const FORECASTER_CODE_ADAPTIVE: u8 = 5;

/// A hashed snapshot of adaptive state at `through_period`.
///
/// `m[tau][cell]` multiplies the frozen per-cell quantile when serving any
/// period *after* `through_period`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Checkpoint {
    pub schema: String,
    pub profile: String,
    pub artefact_sha256: String,
    pub through_period: String,
    pub gamma: f64,
    pub m_floor: f64,
    pub m_ceil: f64,
    pub n_periods_replayed: u64,
    /// Outer key is the tau anchor formatted `"{:.4}"`; inner key is the cell.
    pub m: BTreeMap<String, BTreeMap<String, f64>>,
    #[serde(default)]
    pub checkpoint_sha256: String,
}

impl Checkpoint {
    /// Deterministic serialisation — the pre-image of the hash.
    ///
    /// Must match `adaptive_state.Checkpoint.canonical()` byte for byte.
    /// Hand-built rather than derived through `serde_json`, because the
    /// numeric fields are emitted as fixed-precision *strings* and a derived
    /// impl would emit them as JSON numbers.
    pub fn canonical(&self) -> String {
        let mut s = String::from("{");
        s.push_str(&format!(
            "\"artefact_sha256\":{},",
            json_str(&self.artefact_sha256)
        ));
        s.push_str(&format!("\"gamma\":\"{:.10}\",", self.gamma));
        // `m` is a BTreeMap of BTreeMaps, so both levels are already in the
        // lexical order Python's sort_keys=True produces.
        s.push_str("\"m\":{");
        for (i, (tau, row)) in self.m.iter().enumerate() {
            if i > 0 {
                s.push(',');
            }
            s.push_str(&format!("{}:{{", json_str(tau)));
            for (j, (cell, v)) in row.iter().enumerate() {
                if j > 0 {
                    s.push(',');
                }
                s.push_str(&format!("{}:\"{:.10}\"", json_str(cell), v));
            }
            s.push('}');
        }
        s.push_str("},");
        s.push_str(&format!("\"m_ceil\":\"{:.10}\",", self.m_ceil));
        s.push_str(&format!("\"m_floor\":\"{:.10}\",", self.m_floor));
        s.push_str(&format!(
            "\"n_periods_replayed\":{},",
            self.n_periods_replayed
        ));
        s.push_str(&format!("\"profile\":{},", json_str(&self.profile)));
        s.push_str(&format!("\"schema\":{},", json_str(&self.schema)));
        s.push_str(&format!(
            "\"through_period\":{}",
            json_str(&self.through_period)
        ));
        s.push('}');
        s
    }

    pub fn compute_sha256(&self) -> String {
        let mut h = Sha256::new();
        h.update(self.canonical().as_bytes());
        hex::encode(h.finalize())
    }

    /// True when the stored hash matches the state it claims to cover.
    pub fn verify_self(&self) -> bool {
        !self.checkpoint_sha256.is_empty() && self.checkpoint_sha256 == self.compute_sha256()
    }

    /// Serving-time lookup.
    ///
    /// An unknown cell falls back to 1.0 — a cell with no accumulated state
    /// serves the frozen quantile unmodified, the conservative reading. An
    /// unaudited tau is an **error**, not an interpolation: the checkpoint
    /// authorises multipliers at specific anchors and inventing one between
    /// them would serve a number nobody audited.
    pub fn multiplier_for(&self, cell: &str, tau: f64) -> Result<f64> {
        let key = format!("{tau:.4}");
        let row = self.m.get(&key).ok_or_else(|| {
            Error::Integrity(format!(
                "checkpoint carries no state for tau={tau}; served anchors are {:?}",
                self.m.keys().collect::<Vec<_>>()
            ))
        })?;
        Ok(row.get(cell).copied().unwrap_or(1.0))
    }
}

/// Escape a string as a JSON scalar, matching `json.dumps` for the character
/// classes that appear in checkpoint keys and values (ASCII identifiers,
/// dates, hex digests).
fn json_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Half-width under the adaptive profile:
/// `m[tau][cell] * q_cell(tau) * sigma_hat * prev_close`.
pub fn adaptive_half_width(
    m_regime: f64,
    q_regime: f64,
    sigma_hat: f64,
    prev_close: f64,
) -> f64 {
    m_regime * q_regime * sigma_hat * prev_close
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cp() -> Checkpoint {
        let mut inner = BTreeMap::new();
        inner.insert("normal".to_string(), 1.0);
        let mut m = BTreeMap::new();
        m.insert("0.9500".to_string(), inner);
        Checkpoint {
            schema: "soothsayer.adaptive_state.v1".into(),
            profile: "overnight".into(),
            artefact_sha256: "abc".into(),
            through_period: "2026-04-23".into(),
            gamma: 0.05,
            m_floor: 0.25,
            m_ceil: 4.0,
            n_periods_replayed: 3,
            m,
            checkpoint_sha256: String::new(),
        }
    }

    #[test]
    fn unknown_cell_falls_back_to_unity() {
        assert_eq!(cp().multiplier_for("never_seen", 0.95).unwrap(), 1.0);
    }

    #[test]
    fn unaudited_tau_is_an_error_not_an_interpolation() {
        assert!(cp().multiplier_for("normal", 0.85).is_err());
    }

    #[test]
    fn tampering_breaks_self_verification() {
        let mut c = cp();
        c.checkpoint_sha256 = c.compute_sha256();
        assert!(c.verify_self());
        c.m.get_mut("0.9500").unwrap().insert("normal".into(), 1.5);
        assert!(!c.verify_self());
    }
}
