//! Python ↔ Rust parity for the checkpointed adaptive path (W15, overnight).
//!
//! The fixture (`fixtures/adaptive_parity.json`) is generated by
//! `scripts/gen_adaptive_parity_fixture.py` from the real overnight
//! checkpoint, and this suite requires the Rust implementation to reproduce
//! the canonical pre-image **byte for byte**, the digest exactly, and every
//! served half-width to ≤ 1e-9.
//!
//! Why byte-level and not just digest-level: a digest comparison tells you
//! two implementations disagree but not *where*. Since the pre-image is what
//! a third-party auditor recomputes, a divergence there means a Rust verifier
//! rejects an honest checkpoint — a failure that presents as fraud detection
//! and is actually a port bug. Comparing the string localises it immediately.

use std::collections::BTreeMap;

use serde_json::Value;
use soothsayer_oracle::adaptive::{adaptive_half_width, Checkpoint};

const FIXTURE: &str = include_str!("fixtures/adaptive_parity.json");

fn close(a: f64, b: f64) -> bool {
    let tol = 1e-9_f64.max(1e-9 * b.abs());
    (a - b).abs() <= tol
}

fn checkpoint(fx: &Value) -> Checkpoint {
    let c = &fx["checkpoint"];
    let mut m: BTreeMap<String, BTreeMap<String, f64>> = BTreeMap::new();
    for (tau, row) in c["m"].as_object().unwrap() {
        let mut inner = BTreeMap::new();
        for (cell, v) in row.as_object().unwrap() {
            inner.insert(cell.clone(), v.as_f64().unwrap());
        }
        m.insert(tau.clone(), inner);
    }
    Checkpoint {
        schema: c["schema"].as_str().unwrap().to_string(),
        profile: c["profile"].as_str().unwrap().to_string(),
        artefact_sha256: c["artefact_sha256"].as_str().unwrap().to_string(),
        through_period: c["through_period"].as_str().unwrap().to_string(),
        gamma: c["gamma"].as_f64().unwrap(),
        m_floor: c["m_floor"].as_f64().unwrap(),
        m_ceil: c["m_ceil"].as_f64().unwrap(),
        n_periods_replayed: c["n_periods_replayed"].as_u64().unwrap(),
        m,
        checkpoint_sha256: c["checkpoint_sha256"].as_str().unwrap().to_string(),
    }
}

/// The load-bearing test. Everything else is downstream of this string.
#[test]
fn canonical_preimage_is_byte_identical() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    let expected = fx["canonical"].as_str().unwrap();
    let got = checkpoint(&fx).canonical();
    assert_eq!(
        got, expected,
        "canonical pre-image diverged from Python — a Rust verifier would \
         reject honest checkpoints"
    );
}

#[test]
fn digest_matches_python() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    assert_eq!(checkpoint(&fx).compute_sha256(), fx["sha256"].as_str().unwrap());
}

#[test]
fn published_checkpoint_self_verifies() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    assert!(checkpoint(&fx).verify_self());
}

#[test]
fn multiplier_lookup_parity() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    let ck = checkpoint(&fx);
    for case in fx["multipliers"].as_array().unwrap() {
        let cell = case["cell"].as_str().unwrap();
        let tau = case["tau"].as_f64().unwrap();
        let want = case["m"].as_f64().unwrap();
        let got = ck.multiplier_for(cell, tau).unwrap();
        assert!(close(got, want), "m[{tau}][{cell}]: rust {got} vs python {want}");
    }
}

#[test]
fn served_half_width_parity() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    for case in fx["bands"].as_array().unwrap() {
        let got = adaptive_half_width(
            case["m"].as_f64().unwrap(),
            case["q"].as_f64().unwrap(),
            case["sigma_hat"].as_f64().unwrap(),
            case["prev_close"].as_f64().unwrap(),
        );
        let want = case["half_width"].as_f64().unwrap();
        assert!(close(got, want), "half_width: rust {got} vs python {want}");
    }
}

/// Fixed-precision formatting is the likeliest cross-language divergence —
/// Python and Rust do not agree on rounding for every tie. The pre-image
/// depends on it, so pin it directly rather than hoping the checkpoint's own
/// values never land on a tie.
#[test]
fn fixed_precision_formatting_parity() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    for case in fx["edge_floats"].as_array().unwrap() {
        let v = case["value"].as_f64().unwrap();
        let want = case["formatted"].as_str().unwrap();
        let got = format!("{v:.10}");
        assert_eq!(got, want, "format({v}): rust {got} vs python {want}");
    }
}

/// An unaudited tau must be an error, never an interpolation — the
/// checkpoint authorises multipliers at specific anchors only.
#[test]
fn unaudited_tau_refused() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    assert!(checkpoint(&fx).multiplier_for("normal", 0.8123).is_err());
}

/// A re-sealed forgery must still fail recomputation. Sealing hides a bare
/// edit from `verify_self`; only recomputing the digest from the state
/// catches it, and that is the property the pre-commitment story rests on.
#[test]
fn resealed_tamper_is_still_detectable() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    let mut ck = checkpoint(&fx);
    let original = ck.checkpoint_sha256.clone();
    let tau = ck.m.keys().next().unwrap().clone();
    let cell = ck.m[&tau].keys().next().unwrap().clone();
    *ck.m.get_mut(&tau).unwrap().get_mut(&cell).unwrap() *= 1.10;
    ck.checkpoint_sha256 = ck.compute_sha256(); // re-seal
    assert!(ck.verify_self(), "re-sealing hides a bare edit, as expected");
    assert_ne!(
        ck.checkpoint_sha256, original,
        "a forged state must not reproduce the published digest"
    );
}
