"""Compose the commit message body for the weekly Kamino rollup.

Called by ``scripts/run_kamino_weekly_rollup.sh`` — emits the multi-line
commit message to stdout. The launchd-driven shell wrapper then passes
that string to ``git commit -m``.

Underscored filename signals "internal helper, not a top-level entry point"
so it's not tab-completed alongside the user-facing scripts/ inventory.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def main(weekend_json: str) -> None:
    data = json.loads(Path(weekend_json).read_text())
    rows = data["rows"]
    n = len(rows)
    fri = data["friday"]
    mon = data["monday"]

    lines: list[str] = []
    lines.append(f"chore(kamino-comparator): weekly rollup — weekend {fri} → {mon}")
    lines.append("")

    # Per-symbol realized gap.
    gaps = ", ".join(f"{r['symbol']}={r['realized_gap_bps']:+.0f}" for r in rows)
    lines.append("Per-symbol realized gap (bps):")
    lines.append(f"  {gaps}")
    lines.append("")

    # LTV-gap breach summary.
    n_breached = sum(1 for r in rows if r["ltv_gap_breach"]["realized_breach"])
    lines.append(f"LTV-gap breaches: {n_breached}/{n} (max-LTV-borrower trigger crossed)")

    methods = (
        ("soothsayer_t085",  "Soothsayer τ=0.85"),
        ("soothsayer_t095",  "Soothsayer τ=0.95"),
        ("kamino_incumbent", "Kamino-incumbent"),
        ("simple_heuristic", "simple heuristic"),
    )
    for key, label in methods:
        counts = {"matched": 0, "preemptive": 0, "missed": 0, "silent_safe": 0}
        for r in rows:
            cls = r["ltv_gap_breach"]["methods"].get(key, {}).get("classification", "n/a")
            if cls in counts:
                counts[cls] += 1
        lines.append(
            f"  {label}: "
            f"{counts['matched']}m / {counts['preemptive']}p / "
            f"{counts['missed']}miss / {counts['silent_safe']}silent"
        )
    lines.append("")

    # Tape coverage and snapshot date.
    v5 = sum(int(r.get("v5_tape_n_obs", 0)) for r in rows)
    scope = sum(int(r.get("scope_tape_n_obs", 0)) for r in rows)
    lines.append(f"Tape coverage: v5={v5} rows, scope={scope} rows.")
    lines.append(f"Reserve config snapshot: {data['snapshot_used']}.")
    lines.append("")

    # Optional: surface any reserve-config changes (would require diffing
    # against the previous snapshot). For the v1 wrapper we skip this and
    # let governance changes show up in the weekly markdown report.

    lines.append(
        "Auto-generated by the launchd weekly rollup job "
        "(scripts/run_kamino_weekly_rollup.sh)."
    )

    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <weekend_comparison_*.json>")
    main(sys.argv[1])
