//! Parity against the Python/scipy ground truth.
//!
//! The fixture (`fixtures/parity.json`) is generated by
//! `scripts/gen_verify_parity_fixture.py` from `scipy.stats.chi2` and
//! `soothsayer.backtest.metrics` — including the real forward-tape
//! violation panel — and this suite requires the independent Rust
//! implementations to reproduce every value to ≤ 1e-9.

use serde_json::Value;
use soothsayer_verify::stats;

const FIXTURE: &str = include_str!("fixtures/parity.json");

fn close(a: f64, b: f64) -> bool {
    let tol = 1e-9_f64.max(1e-9 * b.abs());
    (a - b).abs() <= tol
}

fn assert_matches(rust: f64, fixture: &Value, ctx: &str) {
    match fixture.as_f64() {
        Some(expected) => assert!(
            close(rust, expected),
            "{ctx}: rust {rust} vs python {expected}"
        ),
        None => assert!(rust.is_nan(), "{ctx}: rust {rust} vs python NaN"),
    }
}

fn violations(v: &Value) -> Vec<u8> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as u8)
        .collect()
}

#[test]
fn chi2_sf_parity() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    for case in fx["chi2_sf"].as_array().unwrap() {
        let x = case["x"].as_f64().unwrap();
        let df = case["df"].as_u64().unwrap() as u32;
        let got = stats::chi2_sf(x, df);
        assert_matches(got, &case["sf"], &format!("chi2_sf({x}, {df})"));
    }
}

#[test]
fn kupiec_parity() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    for case in fx["kupiec"].as_array().unwrap() {
        let v = violations(&case["violations"]);
        let claimed = case["claimed"].as_f64().unwrap();
        let (lr, p) = stats::kupiec(&v, claimed);
        let ctx = format!("kupiec(n={}, claimed={claimed})", v.len());
        assert_matches(lr, &case["lr"], &format!("{ctx} lr"));
        assert_matches(p, &case["p"], &format!("{ctx} p"));
    }
}

#[test]
fn christoffersen_parity() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    for case in fx["christoffersen"].as_array().unwrap() {
        let v = violations(&case["violations"]);
        let (lr, p) = stats::christoffersen_independence(&v);
        let ctx = format!("christoffersen(n={})", v.len());
        assert_matches(lr, &case["lr"], &format!("{ctx} lr"));
        assert_matches(p, &case["p"], &format!("{ctx} p"));
    }
}

/// The integration-grade case: the real 12-weekend forward panel must
/// reproduce the pooled statistics the weekly report prints.
#[test]
fn forward_tape_parity() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    for case in fx["forward_tape"].as_array().unwrap() {
        let claimed = case["claimed"].as_f64().unwrap();
        let by_symbol = case["violations_by_symbol"].as_object().unwrap();
        // BTreeMap-like: serde_json object preserves insertion order,
        // which the generator writes sorted by symbol.
        let groups: Vec<Vec<u8>> = by_symbol.values().map(violations).collect();
        let all: Vec<u8> = groups.iter().flatten().copied().collect();

        let (k_lr, k_p) = stats::kupiec(&all, claimed);
        assert_matches(k_lr, &case["kupiec_lr"], &format!("fwd τ={claimed} kupiec lr"));
        assert_matches(k_p, &case["kupiec_p"], &format!("fwd τ={claimed} kupiec p"));

        let (c_lr, c_df, c_p) = stats::pooled_independence(&groups);
        assert_eq!(
            c_df as u64,
            case["christ_df"].as_u64().unwrap(),
            "fwd τ={claimed} christ df"
        );
        assert_matches(c_lr, &case["christ_lr"], &format!("fwd τ={claimed} christ lr"));
        assert_matches(c_p, &case["christ_p"], &format!("fwd τ={claimed} christ p"));
    }
}
